name: Maintenance - Pre-Commit
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: # Enables on-demand/manual triggering: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow

jobs:
  pre-commit-maintenance:
    if: github.repository == vars.ORG_WORKLOAD_CORE_INFRA_REPO
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1

      - id: generate-token
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: ${{ secrets.AB_BOT_APP_ID }}
          private-key: ${{ secrets.AB_BOT_PRIVATE_KEY }}

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - id: pre-commit-updates
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          pip install pre-commit
          precommitoutput=$(pre-commit autoupdate)
          precommitupdates=$(echo "$precommitoutput" | grep updating || true)
          echo "precommit_updates<<EOF" >> $GITHUB_OUTPUT
          echo "$precommitupdates" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: |
            Update Precommit Hook Versions
          body: |
            ${{ steps.pre-commit-updates.outputs.precommit_updates }}

            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          delete-branch: true
          branch: create-pull-request/maintenance-precommit
          title: maintenance(precommit) - Update Precommit Hook Versions
          labels: dependencies
